# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bazin_q/rendu/CPP/cpp_indie_studio

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bazin_q/rendu/CPP/cpp_indie_studio

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bazin_q/rendu/CPP/cpp_indie_studio/CMakeFiles /home/bazin_q/rendu/CPP/cpp_indie_studio/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bazin_q/rendu/CPP/cpp_indie_studio/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named indie_studio

# Build rule for target.
indie_studio: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 indie_studio
.PHONY : indie_studio

# fast build rule for target.
indie_studio/fast:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/build
.PHONY : indie_studio/fast

external/tinyxml2.o: external/tinyxml2.cpp.o

.PHONY : external/tinyxml2.o

# target to build an object file
external/tinyxml2.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/external/tinyxml2.cpp.o
.PHONY : external/tinyxml2.cpp.o

external/tinyxml2.i: external/tinyxml2.cpp.i

.PHONY : external/tinyxml2.i

# target to preprocess a source file
external/tinyxml2.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/external/tinyxml2.cpp.i
.PHONY : external/tinyxml2.cpp.i

external/tinyxml2.s: external/tinyxml2.cpp.s

.PHONY : external/tinyxml2.s

# target to generate assembly for a file
external/tinyxml2.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/external/tinyxml2.cpp.s
.PHONY : external/tinyxml2.cpp.s

source/MyTestRoom.o: source/MyTestRoom.cpp.o

.PHONY : source/MyTestRoom.o

# target to build an object file
source/MyTestRoom.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/source/MyTestRoom.cpp.o
.PHONY : source/MyTestRoom.cpp.o

source/MyTestRoom.i: source/MyTestRoom.cpp.i

.PHONY : source/MyTestRoom.i

# target to preprocess a source file
source/MyTestRoom.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/source/MyTestRoom.cpp.i
.PHONY : source/MyTestRoom.cpp.i

source/MyTestRoom.s: source/MyTestRoom.cpp.s

.PHONY : source/MyTestRoom.s

# target to generate assembly for a file
source/MyTestRoom.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/source/MyTestRoom.cpp.s
.PHONY : source/MyTestRoom.cpp.s

source/core/Application.o: source/core/Application.cpp.o

.PHONY : source/core/Application.o

# target to build an object file
source/core/Application.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/source/core/Application.cpp.o
.PHONY : source/core/Application.cpp.o

source/core/Application.i: source/core/Application.cpp.i

.PHONY : source/core/Application.i

# target to preprocess a source file
source/core/Application.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/source/core/Application.cpp.i
.PHONY : source/core/Application.cpp.i

source/core/Application.s: source/core/Application.cpp.s

.PHONY : source/core/Application.s

# target to generate assembly for a file
source/core/Application.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/source/core/Application.cpp.s
.PHONY : source/core/Application.cpp.s

source/core/Timer.o: source/core/Timer.cpp.o

.PHONY : source/core/Timer.o

# target to build an object file
source/core/Timer.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/source/core/Timer.cpp.o
.PHONY : source/core/Timer.cpp.o

source/core/Timer.i: source/core/Timer.cpp.i

.PHONY : source/core/Timer.i

# target to preprocess a source file
source/core/Timer.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/source/core/Timer.cpp.i
.PHONY : source/core/Timer.cpp.i

source/core/Timer.s: source/core/Timer.cpp.s

.PHONY : source/core/Timer.s

# target to generate assembly for a file
source/core/Timer.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/source/core/Timer.cpp.s
.PHONY : source/core/Timer.cpp.s

source/core/XMLFile.o: source/core/XMLFile.cpp.o

.PHONY : source/core/XMLFile.o

# target to build an object file
source/core/XMLFile.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/source/core/XMLFile.cpp.o
.PHONY : source/core/XMLFile.cpp.o

source/core/XMLFile.i: source/core/XMLFile.cpp.i

.PHONY : source/core/XMLFile.i

# target to preprocess a source file
source/core/XMLFile.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/source/core/XMLFile.cpp.i
.PHONY : source/core/XMLFile.cpp.i

source/core/XMLFile.s: source/core/XMLFile.cpp.s

.PHONY : source/core/XMLFile.s

# target to generate assembly for a file
source/core/XMLFile.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/source/core/XMLFile.cpp.s
.PHONY : source/core/XMLFile.cpp.s

source/core/input/GamePad.o: source/core/input/GamePad.cpp.o

.PHONY : source/core/input/GamePad.o

# target to build an object file
source/core/input/GamePad.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/source/core/input/GamePad.cpp.o
.PHONY : source/core/input/GamePad.cpp.o

source/core/input/GamePad.i: source/core/input/GamePad.cpp.i

.PHONY : source/core/input/GamePad.i

# target to preprocess a source file
source/core/input/GamePad.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/source/core/input/GamePad.cpp.i
.PHONY : source/core/input/GamePad.cpp.i

source/core/input/GamePad.s: source/core/input/GamePad.cpp.s

.PHONY : source/core/input/GamePad.s

# target to generate assembly for a file
source/core/input/GamePad.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/source/core/input/GamePad.cpp.s
.PHONY : source/core/input/GamePad.cpp.s

source/core/input/KeyboardHandler.o: source/core/input/KeyboardHandler.cpp.o

.PHONY : source/core/input/KeyboardHandler.o

# target to build an object file
source/core/input/KeyboardHandler.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/source/core/input/KeyboardHandler.cpp.o
.PHONY : source/core/input/KeyboardHandler.cpp.o

source/core/input/KeyboardHandler.i: source/core/input/KeyboardHandler.cpp.i

.PHONY : source/core/input/KeyboardHandler.i

# target to preprocess a source file
source/core/input/KeyboardHandler.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/source/core/input/KeyboardHandler.cpp.i
.PHONY : source/core/input/KeyboardHandler.cpp.i

source/core/input/KeyboardHandler.s: source/core/input/KeyboardHandler.cpp.s

.PHONY : source/core/input/KeyboardHandler.s

# target to generate assembly for a file
source/core/input/KeyboardHandler.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/source/core/input/KeyboardHandler.cpp.s
.PHONY : source/core/input/KeyboardHandler.cpp.s

source/core/states/GameState.o: source/core/states/GameState.cpp.o

.PHONY : source/core/states/GameState.o

# target to build an object file
source/core/states/GameState.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/source/core/states/GameState.cpp.o
.PHONY : source/core/states/GameState.cpp.o

source/core/states/GameState.i: source/core/states/GameState.cpp.i

.PHONY : source/core/states/GameState.i

# target to preprocess a source file
source/core/states/GameState.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/source/core/states/GameState.cpp.i
.PHONY : source/core/states/GameState.cpp.i

source/core/states/GameState.s: source/core/states/GameState.cpp.s

.PHONY : source/core/states/GameState.s

# target to generate assembly for a file
source/core/states/GameState.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/source/core/states/GameState.cpp.s
.PHONY : source/core/states/GameState.cpp.s

source/main.o: source/main.cpp.o

.PHONY : source/main.o

# target to build an object file
source/main.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/source/main.cpp.o
.PHONY : source/main.cpp.o

source/main.i: source/main.cpp.i

.PHONY : source/main.i

# target to preprocess a source file
source/main.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/source/main.cpp.i
.PHONY : source/main.cpp.i

source/main.s: source/main.cpp.s

.PHONY : source/main.s

# target to generate assembly for a file
source/main.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/source/main.cpp.s
.PHONY : source/main.cpp.s

source/resources/ResourceHandler.o: source/resources/ResourceHandler.cpp.o

.PHONY : source/resources/ResourceHandler.o

# target to build an object file
source/resources/ResourceHandler.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/source/resources/ResourceHandler.cpp.o
.PHONY : source/resources/ResourceHandler.cpp.o

source/resources/ResourceHandler.i: source/resources/ResourceHandler.cpp.i

.PHONY : source/resources/ResourceHandler.i

# target to preprocess a source file
source/resources/ResourceHandler.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/source/resources/ResourceHandler.cpp.i
.PHONY : source/resources/ResourceHandler.cpp.i

source/resources/ResourceHandler.s: source/resources/ResourceHandler.cpp.s

.PHONY : source/resources/ResourceHandler.s

# target to generate assembly for a file
source/resources/ResourceHandler.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/source/resources/ResourceHandler.cpp.s
.PHONY : source/resources/ResourceHandler.cpp.s

source/scene/Scene.o: source/scene/Scene.cpp.o

.PHONY : source/scene/Scene.o

# target to build an object file
source/scene/Scene.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/source/scene/Scene.cpp.o
.PHONY : source/scene/Scene.cpp.o

source/scene/Scene.i: source/scene/Scene.cpp.i

.PHONY : source/scene/Scene.i

# target to preprocess a source file
source/scene/Scene.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/source/scene/Scene.cpp.i
.PHONY : source/scene/Scene.cpp.i

source/scene/Scene.s: source/scene/Scene.cpp.s

.PHONY : source/scene/Scene.s

# target to generate assembly for a file
source/scene/Scene.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/source/scene/Scene.cpp.s
.PHONY : source/scene/Scene.cpp.s

source/scene/factories/SinbadFactory.o: source/scene/factories/SinbadFactory.cpp.o

.PHONY : source/scene/factories/SinbadFactory.o

# target to build an object file
source/scene/factories/SinbadFactory.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/source/scene/factories/SinbadFactory.cpp.o
.PHONY : source/scene/factories/SinbadFactory.cpp.o

source/scene/factories/SinbadFactory.i: source/scene/factories/SinbadFactory.cpp.i

.PHONY : source/scene/factories/SinbadFactory.i

# target to preprocess a source file
source/scene/factories/SinbadFactory.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/source/scene/factories/SinbadFactory.cpp.i
.PHONY : source/scene/factories/SinbadFactory.cpp.i

source/scene/factories/SinbadFactory.s: source/scene/factories/SinbadFactory.cpp.s

.PHONY : source/scene/factories/SinbadFactory.s

# target to generate assembly for a file
source/scene/factories/SinbadFactory.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/source/scene/factories/SinbadFactory.cpp.s
.PHONY : source/scene/factories/SinbadFactory.cpp.s

source/scene/system/AnimationSystem.o: source/scene/system/AnimationSystem.cpp.o

.PHONY : source/scene/system/AnimationSystem.o

# target to build an object file
source/scene/system/AnimationSystem.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/source/scene/system/AnimationSystem.cpp.o
.PHONY : source/scene/system/AnimationSystem.cpp.o

source/scene/system/AnimationSystem.i: source/scene/system/AnimationSystem.cpp.i

.PHONY : source/scene/system/AnimationSystem.i

# target to preprocess a source file
source/scene/system/AnimationSystem.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/source/scene/system/AnimationSystem.cpp.i
.PHONY : source/scene/system/AnimationSystem.cpp.i

source/scene/system/AnimationSystem.s: source/scene/system/AnimationSystem.cpp.s

.PHONY : source/scene/system/AnimationSystem.s

# target to generate assembly for a file
source/scene/system/AnimationSystem.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/source/scene/system/AnimationSystem.cpp.s
.PHONY : source/scene/system/AnimationSystem.cpp.s

source/scene/system/CollisionSystem.o: source/scene/system/CollisionSystem.cpp.o

.PHONY : source/scene/system/CollisionSystem.o

# target to build an object file
source/scene/system/CollisionSystem.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/source/scene/system/CollisionSystem.cpp.o
.PHONY : source/scene/system/CollisionSystem.cpp.o

source/scene/system/CollisionSystem.i: source/scene/system/CollisionSystem.cpp.i

.PHONY : source/scene/system/CollisionSystem.i

# target to preprocess a source file
source/scene/system/CollisionSystem.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/source/scene/system/CollisionSystem.cpp.i
.PHONY : source/scene/system/CollisionSystem.cpp.i

source/scene/system/CollisionSystem.s: source/scene/system/CollisionSystem.cpp.s

.PHONY : source/scene/system/CollisionSystem.s

# target to generate assembly for a file
source/scene/system/CollisionSystem.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/source/scene/system/CollisionSystem.cpp.s
.PHONY : source/scene/system/CollisionSystem.cpp.s

source/scene/system/MovementSystem.o: source/scene/system/MovementSystem.cpp.o

.PHONY : source/scene/system/MovementSystem.o

# target to build an object file
source/scene/system/MovementSystem.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/source/scene/system/MovementSystem.cpp.o
.PHONY : source/scene/system/MovementSystem.cpp.o

source/scene/system/MovementSystem.i: source/scene/system/MovementSystem.cpp.i

.PHONY : source/scene/system/MovementSystem.i

# target to preprocess a source file
source/scene/system/MovementSystem.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/source/scene/system/MovementSystem.cpp.i
.PHONY : source/scene/system/MovementSystem.cpp.i

source/scene/system/MovementSystem.s: source/scene/system/MovementSystem.cpp.s

.PHONY : source/scene/system/MovementSystem.s

# target to generate assembly for a file
source/scene/system/MovementSystem.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/source/scene/system/MovementSystem.cpp.s
.PHONY : source/scene/system/MovementSystem.cpp.s

source/scene/system/SceneSystem.o: source/scene/system/SceneSystem.cpp.o

.PHONY : source/scene/system/SceneSystem.o

# target to build an object file
source/scene/system/SceneSystem.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/source/scene/system/SceneSystem.cpp.o
.PHONY : source/scene/system/SceneSystem.cpp.o

source/scene/system/SceneSystem.i: source/scene/system/SceneSystem.cpp.i

.PHONY : source/scene/system/SceneSystem.i

# target to preprocess a source file
source/scene/system/SceneSystem.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/source/scene/system/SceneSystem.cpp.i
.PHONY : source/scene/system/SceneSystem.cpp.i

source/scene/system/SceneSystem.s: source/scene/system/SceneSystem.cpp.s

.PHONY : source/scene/system/SceneSystem.s

# target to generate assembly for a file
source/scene/system/SceneSystem.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/source/scene/system/SceneSystem.cpp.s
.PHONY : source/scene/system/SceneSystem.cpp.s

source/system/GameClock.o: source/system/GameClock.cpp.o

.PHONY : source/system/GameClock.o

# target to build an object file
source/system/GameClock.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/source/system/GameClock.cpp.o
.PHONY : source/system/GameClock.cpp.o

source/system/GameClock.i: source/system/GameClock.cpp.i

.PHONY : source/system/GameClock.i

# target to preprocess a source file
source/system/GameClock.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/source/system/GameClock.cpp.i
.PHONY : source/system/GameClock.cpp.i

source/system/GameClock.s: source/system/GameClock.cpp.s

.PHONY : source/system/GameClock.s

# target to generate assembly for a file
source/system/GameClock.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/source/system/GameClock.cpp.s
.PHONY : source/system/GameClock.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... indie_studio"
	@echo "... external/tinyxml2.o"
	@echo "... external/tinyxml2.i"
	@echo "... external/tinyxml2.s"
	@echo "... source/MyTestRoom.o"
	@echo "... source/MyTestRoom.i"
	@echo "... source/MyTestRoom.s"
	@echo "... source/core/Application.o"
	@echo "... source/core/Application.i"
	@echo "... source/core/Application.s"
	@echo "... source/core/Timer.o"
	@echo "... source/core/Timer.i"
	@echo "... source/core/Timer.s"
	@echo "... source/core/XMLFile.o"
	@echo "... source/core/XMLFile.i"
	@echo "... source/core/XMLFile.s"
	@echo "... source/core/input/GamePad.o"
	@echo "... source/core/input/GamePad.i"
	@echo "... source/core/input/GamePad.s"
	@echo "... source/core/input/KeyboardHandler.o"
	@echo "... source/core/input/KeyboardHandler.i"
	@echo "... source/core/input/KeyboardHandler.s"
	@echo "... source/core/states/GameState.o"
	@echo "... source/core/states/GameState.i"
	@echo "... source/core/states/GameState.s"
	@echo "... source/main.o"
	@echo "... source/main.i"
	@echo "... source/main.s"
	@echo "... source/resources/ResourceHandler.o"
	@echo "... source/resources/ResourceHandler.i"
	@echo "... source/resources/ResourceHandler.s"
	@echo "... source/scene/Scene.o"
	@echo "... source/scene/Scene.i"
	@echo "... source/scene/Scene.s"
	@echo "... source/scene/factories/SinbadFactory.o"
	@echo "... source/scene/factories/SinbadFactory.i"
	@echo "... source/scene/factories/SinbadFactory.s"
	@echo "... source/scene/system/AnimationSystem.o"
	@echo "... source/scene/system/AnimationSystem.i"
	@echo "... source/scene/system/AnimationSystem.s"
	@echo "... source/scene/system/CollisionSystem.o"
	@echo "... source/scene/system/CollisionSystem.i"
	@echo "... source/scene/system/CollisionSystem.s"
	@echo "... source/scene/system/MovementSystem.o"
	@echo "... source/scene/system/MovementSystem.i"
	@echo "... source/scene/system/MovementSystem.s"
	@echo "... source/scene/system/SceneSystem.o"
	@echo "... source/scene/system/SceneSystem.i"
	@echo "... source/scene/system/SceneSystem.s"
	@echo "... source/system/GameClock.o"
	@echo "... source/system/GameClock.i"
	@echo "... source/system/GameClock.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

